echo "> Configure Firefox"

#git clone 

# pref("app.shield.optoutstudies.enabled", false)
# pref("browser.newtabpage.activity-stream.feeds.telemetry", false)
# pref("browser.newtabpage.activity-stream.telemetry", false)
# pref("browser.newtabpage.activity-stream.telemetry.structuredIngestion", false)
# pref("browser.ping-centre.telemetry", false)
# pref("browser.contentblocking.category", "strict")
# pref("toolkit.telemetry.archive.enabled", false)
# pref("toolkit.telemetry.bhrPing.enabled", false)
# pref("toolkit.telemetry.enabled", false)
# pref("toolkit.telemetry.firstShutdownPing.enabled", false)
# pref("toolkit.telemetry.hybridContent.enabled", false)
# pref("toolkit.telemetry.newProfilePing.enabled", false)
# pref("toolkit.telemetry.reportingpolicy.firstRun", false)
# pref("toolkit.telemetry.shutdownPingSender.enabled", false)
# pref("toolkit.telemetry.unified", false)
# pref("toolkit.telemetry.updatePing.enabled", false)
# pref("extensions.experiments.enabled", false)
# pref("signon.rememberSignons", false)
# pref("privacy.donottrackheader.enabled", true)
# pref("privacy.trackingprotection.fingerprinting.enabled", true)
# pref("privacy.trackingprotection.socialtracking.enabled", true)
# pref("privacy.trackingprotection.cryptomining.enabled", true)
# pref("privacy.trackingprotection.enabled", true)
# pref("privacy.resistFingerprinting", true)
# pref("privacy.firstparty.isolate", true)
# pref("geo.enabled", true)
# pref("media.navigator.enabled", false)
# pref("network.cookie.cookieBehavior", 1)
# pref("network.dns.disablePrefetch", true)
# pref("network.dns.disablePrefetchFromHTTPS", true)
# pref("network.prefetch-next", false)
# pref("network.predictor.enabled", false)
# pref("network.predictor.enable-prefetch", false)
# pref("webgl.disabled", true)
# pref("dom.event.clipboardevents.enabled", false)
# pref("media.eme.enabled ", false)
# pref("browser.send_pings", false)
# pref("media.gmp-widevinecdm.enabled", false)
# pref("beacon.enabled", false)
# pref("browser.safebrowsing.downloads.remote.enabled", false)
# pref("network.IDN_show_punycode", true)
# pref("browser.newtabpage.activity-stream.feeds.snippets", false)
# pref("browser.newtabpage.activity-stream.feeds.section.highlights", false)
# pref("browser.newtabpage.activity-stream.feeds.topsites", false)
